### ISSUE TITLE
can support e raw tcp/udp protocol of rpc call? 

### ISSUE THREAD

**Issue by yiliaofan** [processone/tsung#115]
Hello 

Do you have any plans to support the raw tcp/udp rpc call ?

well done~  thank you!

Regards, B.

**Comment by nniclausse** [comment]
Tsung already support raw protocol (see ts_raw plugin). The documentation was missing though, fixed in https://github.com/processone/tsung/commit/36a718262b25921b62b00d16b2577f32a4bb8d29
Is it what you are looking for ?

**Comment by alicehanhy** [comment]
How to get the specific string from the Tcp protocol reponse by regexp ? the reponse is "  408005             6188007051562582020", my script is "
 <request>
     <dyn_variable name="sessionID"  re="6[0-9]{18}"/>
      <raw data="00520005150805134521f84409ba6f5f317c6613dc201018caeb" ack="local"></raw>
 </request>  ",but the value of the  variable sessionID is blank.

**Comment by alicehanhy** [comment]
Ok，I've got the result from reponse correctly,the reason was the regexp in tsung should use "()",the correct script as following:re="(6[0-9]{18})"

**Comment by nniclausse** [comment]
ok, fine, I think we can close the issue.

**Comment by alicehanhy** [comment]
Ok




huakaiwusheng_1986

From: Nicolas Niclausse
Date: 2015-09-07 16:27
To: processone/tsung
CC: alicehanhy
Subject: Re: [tsung] can support e raw tcp/udp protocol of rpc call? (#115)
ok, fine, I think we can close the issue.

**Comment by reith** [comment]
Can it work with UDP now?  I cannot make traffic with UDP, using same configuration as raw_tcp example but replaced server type from "tcp" to "udp".

```
<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/share/tsung/tsung-1.0.dtd">
<tsung loglevel="debug" dumptraffic="true" version="1.0">

  <clients>
    <client host="localhost" weight="2" maxusers="10000" use_controller_vm="false"/>
  </clients>

  <servers>
    <server host="127.0.0.1" port="9090" type="udp"></server>
  </servers>

  <load>
    <arrivalphase phase="1" duration="10" unit="minute">
      <users arrivalrate="2" unit="second"></users>
    </arrivalphase>
  </load>


 <sessions>
 <session probability="100" name="raw" type="ts_raw">
    <transaction name="open">
      <request> <raw data="hellloooooo" ack="no_ack"></raw> </request>
    </transaction>
  </session>
 </sessions>
</tsung>
```
From logs:

```
stats: {freemem,"tsung_controller@localhost"} 1 2075.96484375 0.0 2098.55859375 2075.96484375 2088.9544270833335 3
stats: session 18 1.8977186414930556 0.1852411166360447 6.77783203125 1.22900390625 2.0139789003314394 66
stats: users_count 18 84
stats: finish_users_count 18 84
stats: error_unknown 16 82
```

**Comment by joaohf** [comment]
Hi, 

Using the xml above, I got:

````
=INFO REPORT==== 24-May-2016::09:19:45 ===
           ts_client:(7:<0.164.0>) connect to port 7000
=INFO REPORT==== 24-May-2016::09:19:45 ===
           ts_client:(5:<0.164.0>) Stop in state think, reason= badarg

=ERROR REPORT==== 24-May-2016::09:19:45 ===
** State machine <0.164.0> terminating
** Last message in was {timeout,#Ref<0.0.2.523>,end_thinktime}
** When State == think
**      Data  == {state_rcv,none,
                     {{0,0,0,0},0},
                     undefined,0,10000,"localhost",7000,ts_udp,
                     {proto_opts,negotiate,negotiate,"/http-bind/",false,
                         false,"/chat","binary",10,3,600000,infinity,infinity,
                         32768,32768,undefined,undefined,[],true,true},
                     false,1,undefined,true,undefined,-576460734839818548,11,
                     11,false,undefined,0,[],<<>>,
                     {raw,undefined,undefined,undefined},
                     0,33,524288,524288,
                     [{tsung_userid,33}],
                     ts_raw,[],undefined,full}
** Reason for termination =
** badarg
````

**Comment by mit0223** [comment]
Hi,
We faced same problem  when we use the raw request with udp to send syslog packet. We find that the udp transport require the buffer options like followings.
```
<options>
  <option name="udp_snd_buffer" value="16384"></option>
  <option name="udp_rcv_buffer" value="16384"></option>
 </options>
```

I think that the options should be pre-set.

**Comment by reith** [comment]
I hit the same problem while tried to make a DNS stress loader and @mit0223 solution worked. Kudos!
My conclusion is UDP data sending is not possible if buffer size is not set exclusively which looks like a bug.

**Comment by nniclausse** [comment]
yes, it's a bug. Fixed, thanks.
