### ISSUE TITLE
Closing TCP connection in think state considered an error?

### ISSUE THREAD

**Issue by tisba** [processone/tsung#117]
I noticed the following error messages in tsung nodes logs:

```
=INFO REPORT==== 13-May-2015::11:53:55 ===
           ts_client:(3:<0.7014.0>) Error: Unknown msg {tcp_closed,
                                                        #Port<0.133649>} receive in state think, stop
```

While I do think that this might be interesting when debugging things, I think we should properly handle this and only report this on log level `debug`.

/cc @nniclausse

**Comment by nniclausse** [comment]
There's a specific clause for tcp_closed, but it does not match this one (no Data in message); i will handle this one also.

**Comment by tisba** [comment]
Nice, thanks!
