### ISSUE TITLE
error_connection_closed to be confused with error_connect_closed

### ISSUE THREAD

**Issue by tisba** [processone/tsung#119]
I see both errors from time to time which is a bit confusing.

`error_connection_closed`: https://github.com/processone/tsung/blob/master/src/tsung/ts_client.erl#L844
`error_connect_closed`: https://github.com/processone/tsung/blob/master/src/tsung/ts_client.erl#L891

According to https://tsung.readthedocs.org/en/latest/errorslist.html#error-connect-errorname (and that's correct IMO), `error_connect_` prefixed errors indicate an error **while establishing a connection** to the server. So, `error_connect_closed` is correct.

Whereas `error_connection_closed` is reported when the connection is closed **while sending data** to the server. In this case the connection is already established and it should be prefixed with `error_send_` (https://tsung.readthedocs.org/en/latest/errorslist.html#error-send-errorname).

So I propose to rename `error_connection_closed` to `error_send_connection_closed`. I'm happy to provide a pull request.

**Comment by nniclausse** [comment]
I'm ok with this
