### ISSUE TITLE
running tsung behind a proxy

### ISSUE THREAD

**Issue by fabuloso** [processone/tsung#120]
Hi, 
i am trying tsung while evaluating different load tool, but currently I am behind a proxy. 

Is there a way to configure tsung to use my company proxy? 

Thank you

**Comment by nniclausse** [comment]
yes, you should add: <option type="ts_http" name="http_use_server_as_proxy" value="true"></option>

The server configured will used as a proxy and absolute URL must be used in <sessions>

**Comment by fabuloso** [comment]
@nniclausse sorry can you show me how to achieve the result? should i configure the xml file? thanks

**Comment by tisba** [comment]
@nniclausse your response somehow looks being lost :)

@fabuloso I'm not sure what you exactly want to achieve. Do you want to test the proxy server? In this case you might want to take a look at https://tsung.readthedocs.org/en/latest/benchmark.html#benchmarking-a-proxy-server.

**Comment by mattharrington001** [comment]
Could you please give an example of how to specify the proxy server in the input file? This is for the situation where there is a proxy between the client that tsung is running on and the server being tested.

The previous answer "The server configured will used as a proxy and absolute URL must be used in" isn't clear.

Thanks very much for your help!

**Comment by manjukori** [comment]
@nniclausse @mattharrington001 
Could you please provide an example of how to set the https proxy server in the tsung config file?? I have the server under test behind the proxy and "https_proxy" env variable does not have impact on the tsung run.

**Comment by tisba** [comment]
I took the liberty to fix @nniclausse comment :) Also, please take a look at the documentation: https://tsung.readthedocs.org/en/latest/benchmark.html#benchmarking-a-proxy-server. If you set this option, and use absolute URLs for your `<http url="…">` tsung will use the provided `<servers>` as HTTP proxies.

Is this what you are looking for, @mattharrington001, @manjukori, @fabuloso?

**Comment by manjukori** [comment]
@tisba Thanks, yes using absolute URLs will work for me. However, I am seeing SSL certificate validation errors, is there a option in Tsung to ignore such SSL errors. 
[Something like in python requests lib, response = requests.get(url, verify=False), verify=False will ignore SSL certificate error]

**Comment by tisba** [comment]
That's strange. Can you paste parts of your error log? IIRC by default tsung does not perform certificate validation…

**Comment by manjukori** [comment]
I was getting 403 error from proxy with invalid certificate. I will try check the proxy first and make sure if that behaving correctly. Thanks for your reply.

**Comment by tisba** [comment]
You're welcome!

I'll close this issue now. Feel free to comment again if you still have issues with this feature.
