### ISSUE TITLE
Unable to send a line feed in websoscket request

### ISSUE THREAD

**Issue by gtokvoth** [processone/tsung#121]
An example that does not work.

```
    <request>
        <websocket type="message">echo test message\n</websocket>
    </request>  
```

**Comment by tisba** [comment]
Since tsung uses an XML configuration, you need to encode the `\n` properly (e.g. using `&#10;`).

**Comment by gtokvoth** [comment]
Thanks for your reply.

I have tried that and it doesn’t work. It always seems to strip out the CR or LF.

Here is what I have tried.

&#10;

<websocket type="message" frame="text">echo message&#10;</websocket>

&#10;\n

<websocket type="message" frame="text">echo message&#10;\n</websocket>

CDATA

<websocket type="message" frame="text"><![CDATA[echo message&#10;]]></websocket>

I have also tried CDATA with an actual line break in the editor as well as (&#13;) and (&#xd;).

I can provide wireshark traces if you want.

I am attaching my configuration file for your review.

Again thanks for your reply.

Kevin.

**Comment by gtokvoth** [comment]
In addition I an using Tsung version 1.6.0 and it is installed on openSUSE version 13.1.

Thanks …

**Comment by gtokvoth** [comment]
Just wondering if you had any thoughts on the issue I am having.

Thanks …

Kevin.

**Comment by tisba** [comment]
No, I'm not using websocket tests on a regular basis and I have very limited time currently to go through the tsung code. As far as I remember there is nothing special in terms of data handling for websockets, so I thought this would just be an XML encoding issue.

Maybe @nniclausse can help?

**Comment by nniclausse** [comment]
the string was explicitly cleaned by tsung ... i removed the faulty line. Can you try the latest git version?

**Comment by nniclausse** [comment]
tested with:
<websocket type="message">echo test message
</websocket>

result:
        0x0030:  1e0d dbd6 8112 6563 686f 2074 6573 7420  ......echo.test.
        0x0040:  6d65 7373 6167 650a                      message.

**Comment by gtokvoth** [comment]
Excellent, thanks.

I will try and test it tonight.

**Comment by gtokvoth** [comment]
Yes that worked.

What about encoding the linefeed? I tried &#10; but that did not work.

Thanks for all your help.

Kevin.
