### ISSUE TITLE
ts_os_mon_erlang seems to tear down tsung under load

### ISSUE THREAD

**Issue by tisba** [processone/tsung#130]
I just noticed the following error in the controller's log. I'm not entirely sure, but beginning at this moment no more traffic was generated although tsung was still running.

Any idea why/how this could happen?

```
=ERROR REPORT==== 20-Sep-2015::16:47:43 ===
** Generic server <0.97.0> terminating
** Last message in was {'EXIT',<8910.106.0>,
                           {{badmatch,[]},
                            [{ts_os_mon_erlang,get_os_data,2,
                                 [{file,
                                      "src/tsung_controller/ts_os_mon_erlang.erl"},
                                  {line,255}]},
                             {ts_os_mon_erlang,node_data,0,
                                 [{file,
                                      "src/tsung_controller/ts_os_mon_erlang.erl"},
                                  {line,217}]},
                             {ts_os_mon_erlang,updatestats,3,
                                 [{file,
                                      "src/tsung_controller/ts_os_mon_erlang.erl"},
                                  {line,161}]}]}}
** When Server state == {state,{global,ts_mon},
                               10000,'os_mon@ip-172-31-7-124',
                               "ip-172-31-7-124",<8910.106.0>,[]}
```

**Comment by nniclausse** [comment]
the badmatch is weird, but there was a problem for os_mon running on the controller: the spawn_link was done during init, so the exit signals was not handled by the gen_server itself but by the process who started the gen_server; it may explain the problem observed

**Comment by tisba** [comment]
@nniclausse I think the badmatch occures when there is no (or almost no) free memory available anymore. I just saw this on a bigger test, where the was a lot of memory pressure on the generators and they actually died.

I'm trying to reproduce this to figure out exactly what happens.
