### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by miller15** [processone/tsung#131]
Hello,
I am on Mac OSX 10.10.5 I installed Tsung using homebrew.
I am unable to start tsung with the command "tsung start"
I receive the following output:

        Starting Tsung
        Log directory is: /Users/m30039/.tsung/log/20150923-1402
        Config Error, aborting ! "Can't detect character encoding due to lack of indata"

I have checked the log directory. In it I find a file 1603353!-m30039.log, in which part of the file says:
        Error while parsing XML config file: "Can't detect character encoding due to lack of indata"

I had to manually create the tsung.xml file (it is empty). Do I need to add something in there?

**Comment by miller15** [comment]
Here is some more output in the tsung_controller!@603353!-m30039.log file:


=INFO REPORT==== 23-Sep-2015::14:02:37 ===
    ts_config_server:(5:<0.69.0>) Config server started, logdir is "/Users/m30039/.tsung/log/20150923-1402"
 
=INFO REPORT==== 23-Sep-2015::14:02:37 ===
              ts_mon:(5:<0.50.0>) starting monitor, global 

=INFO REPORT==== 23-Sep-2015::14:02:37 ===
           ts_config:(5:<0.69.0>) Reading config file: /Users/m30039/.tsung/tsung.xml

=ERROR REPORT==== 23-Sep-2015::14:02:37 ===
3901- fatal: expected_element_start_tag

=INFO REPORT==== 23-Sep-2015::14:02:37 ===
    ts_config_server:(0:<0.69.0>) Error while parsing XML config file: "Can't detect character encoding due to lack of indata"

=ERROR REPORT==== 23-Sep-2015::14:02:37 ===
** Generic server ts_config_server terminating 
** Last message in was {get_monitor_hosts}
** When Server state == {state,undefined,
                               "/Users/m30039/.tsung/log/20150923-1402",0,0,0,
                               undefined,1,undefined,'1603353A-m30039',0,0,
                               undefined,undefined}
** Reason for termination == 
** {{badrecord,config},
    [{ts_config_server,handle_call,3,
                       [{file,"src/tsung_controller/ts_config_server.erl"},
                        {line,335}]},
     {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}

=INFO REPORT==== 23-Sep-2015::14:02:37 ===
    ts_config_server:(5:<0.88.0>) Config server started, logdir is "/Users/m30039/.tsung/log/20150923-1402"

**Comment by kbrown** [comment]
What do you expect Tsung to do with an empty config file?

**Comment by miller15** [comment]
I don't know what goes in the config file. Could you provide some guidance?

**Comment by nniclausse** [comment]
there are examples provided files when tsung is installed, and you should of course read the documentation;
the xml file is documented in this section:
http://tsung.erlang-projects.org/user_manual/configuration.html

**Comment by miller15** [comment]
Thank you I appreciate the direction.
