### ISSUE TITLE
tsung suddenly terminated

### ISSUE THREAD

**Issue by umarzuki** [processone/tsung#139]
Tsung version 1.6.1-git
Ubuntu 14.04 amd64

I don't understand why a simple http test would get terminated.

but perferctly fine with binary from http://tsung.erlang-projects.org/dist/ubuntu/trusty/

controller log and tsung xml setting attached.

[tsung_controller@P45VJ.log.txt](https://github.com/processone/tsung/files/38531/tsung_controller.P45VJ.log.txt)

[http_simple.xml.txt](https://github.com/processone/tsung/files/38532/http_simple.xml.txt)

**Comment by bltb** [comment]
There is a bug in the new code for beam spreading.

Until there is a fix, please try commit https://github.com/processone/tsung/commit/e93d2b86c7a5797e638d92e28b3b750c3c7e5b6e .

**Comment by nniclausse** [comment]
It should work now, thanks for reporting the bug.
