### ISSUE TITLE
tsung_record creates invalid xml files

### ISSUE THREAD

**Issue by jefflowrey** [processone/tsung#147]
I'm starting up with a very simple test of tsung.  Following the docs, I set up and run a simple recording session.

The file that is output looks like
<session name='rec20160118-1111' probability='100'  type='ts_http'>
<request><http url='http:/www.example.comima/index.html version='1.1' method='GET'></http></request>
</session>

When I try to use tsung to run this file, I get the following:
Starting Tsung
Log directory is: /root/.tsung/log/20160118-1121
3468- fatal: {error,{error_missing_element_declaration_in_DTD,session}}
Config Error, aborting ! {fatal,
                             {{error,
                                  {error_missing_element_declaration_in_DTD,
                                      session}},
                              {file,"test.xml"},
                              {line,1},
                              {col,2}}}

When I look at the sample xml files, they all start with
<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/share/tsung/tsung-1.0.dtd">
<tsung loglevel="notice" version="1.0">

In addition, the session elements are wrapped within a higher level <sessions> element.

I'm using
tsung-recorder -v
Tsung Recorder version 1.6.0
tsung -v
Tsung version 1.6.0

**Comment by tisba** [comment]
I think there might be room for improvement of the documentation :) The recorder creates "sessions" which are meant to be included in your test configuration.

**Comment by nniclausse** [comment]
As stated in the documentation: http://tsung.erlang-projects.org/user_manual/proxy.html
the recorded session has to be included in a main XML file.
