### ISSUE TITLE
Plugin Tutorial

### ISSUE THREAD

**Issue by GalaxyGorilla** [processone/tsung#155]
According to the references there should be a tutorial on how to write Tsung plugins available at

  http://www.process-one.net/en/wiki/Writing_a_Tsung_plugin/

However, I only get redirected to the process-one front page. Is this tutorial still available somewhere?

**Comment by rds13** [comment]
:+1:

**Comment by mremond** [comment]
Sorry for the broken link. I should be able to solve that this week.

**Comment by zyuyou** [comment]
The link still being broken now 😫

**Comment by yakubovsky** [comment]
Still no tutorial.

**Comment by codertrack** [comment]
kidding me?

**Comment by mremond** [comment]
Tutorial was reposted as Gist: https://gist.github.com/mremond/a5c1c25aad11dfc40ae7b4f18c000942
