### ISSUE TITLE
Tsung won't work when using jdbc:postgresql_autogis

### ISSUE THREAD

**Issue by fnicollet** [processone/tsung#157]
Hello,

We have been trying tsung on our Java program and we are running into issues. When we use the database on port 5432 (straight to postgres), no problem. When we change the port to 8090, we get a jdbc error "unkown protocol". The JDBC url is exactly the same except from the port.
Are there issues related to Tsung and JDBC?

Thanks,
Fabien

**Comment by nniclausse** [comment]
Hello
Tsung does not support the jdbc/odbc protocols. It only support the native postgres protocol

**Comment by fnicollet** [comment]
Thanks, now I understand why we were stuck :)
We ended up creating the Tsung XML from the postgres log (quite hard but not impossible)
