### ISSUE TITLE
"<load duration>" not working along with "<session><for>"?

### ISSUE THREAD

**Issue by mathieumd** [processone/tsung#162]
The FAQ entry [How can i simulate a fix number of users?](http://tsung.erlang-projects.org/user_manual/faq.html#how-can-i-simulate-a-fix-number-of-users) gives a way to fix the number of user, _and_ to specify a duration. So I adapted it to my case, which gives this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tsung SYSTEM "/usr/share/tsung/tsung-1.0.dtd" []>
<tsung loglevel="warning">
  <clients>
    <client host="localhost" use_controller_vm="true"/>
  </clients>
  <servers>
    <server host="example.com" port="80" type="tcp"/>
  </servers>

<load duration="1" unit="minute">
<!-- So it should be stopped after 1 minute -->
  <arrivalphase phase="1" duration="5" unit="minute">
    <users maxnumber="10" arrivalrate="100" unit="second"></users>
  </arrivalphase>
</load>
<sessions>
  <session probability="100" name="ab" type="ts_http">
    <for from="1" to="1000" var="i">
      <request><http url='http://example.com/index.php' version='1.1' method='GET'></http></request>
      <thinktime random='true' value='2'/>
    </for>
  </session>
</sessions>

</tsung>
```

But the execution did actually **not** stopped after **1 minute**, neither after **5 minutes**, but I had to abort it after more than **9 minutes**.

Is the `<for>` loops really also stopped by `duration`?

Tsung version 1.6.1_git

**Comment by nniclausse** [comment]
You are right, the max duration is not enforced when use_controller_vm is true. I'll fix this

**Comment by mathieumd** [comment]
Indeed, you fixed it. Thanks.
