### ISSUE TITLE
How can i using chinese string in the tsung

### ISSUE THREAD

**Issue by domingoxx** [processone/tsung#166]
Hi everyone

I'm china developer, i use `tsung` to test my application.

but now , i have problem,

 this is my xml code.

```
<options>
   <option name="file_server" id="usernames" value="/usr/local/tsung/username.csv" />
  </options>

<sessions>
  <session name='rec20160406-1853' probability='100'  type='ts_http'>
    <setdynvars sourcetype="file" fileid="usernames" delimiter=";">
      <var name="user_name"/>
  </setdynvars>

    <request subst="true">
      <http url='http://10.2.0.96:3000/sessions?username=%%_user_name%%'>
      </http>
    </request>

</session>
 </sessions>
```

username.csv

```
四方茉莉-Ra
宁靜致遠
阿莫西林
脸骑士
大嗨朵
右眼淤青
程子
这明显不科学
冰与火奏鸣曲
```

I want send `user_name` to my application, the `user_name` is read from `csv` file, the `csv` file is chinese content.
I start tsung, and watch the nginx access-log.
log: 

```
192.168.60.61 - - [21/Apr/2016:17:17:29 +0800] "GET /sessions?username=\xE5\x86\xB0\xE4\xB8\x8E\xE7\x81\xAB\xE5\xA5\x8F\xE9\xB8\xA3\xE6\x9B\xB2 HTTP/1.1" 500 70 "-" "tsung"
```

the `user_name` encode to be `\xE5\x86\xB0\xE4\xB8\x8E\xE7\x81\xAB\xE5\xA5\x8F\xE9\xB8\xA3\xE6\x9B\xB2`, my application can not resolve this.
please help me , how can i to do.

**Comment by tisba** [comment]
Hey @DaaarksunWang. This is actually not directly a tsung problem. You need to URL encode your input if you want to use it in a URL. Tsung won't do that for you automatically.

**Comment by tisba** [comment]
I'll close this issue for now. Please feel free to comment if the problem persists.
