### ISSUE TITLE
How can i see the really verbose logging?

### ISSUE THREAD

**Issue by alicehanhy** [processone/tsung#167]
Hi,all:

I want to sedd the really verbose logging,it is that to say to see the debug process,the set is as following:
`<tsung loglevel="debug" dumptraffic="true" version="1.0">
<sessions>
<session probability="100" name="raw" type="ts_raw">
<transaction name="data">
	 <request>
	 	<dyn_variable name="loginTag" re="&lt;success xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot;&gt;(.*)&lt;/success&gt;"/>
	 	 <raw data="&lt;auth xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot; resource=&quot;JMeter&quot;&gt;ADE0MTIxMTEwMDAwADExMTExMQ==&lt;/auth&gt;" ack="local"></raw> 
	 </request>
    </transaction>
 </session>
 </sessions>`
but the tsung.dump like this:
**NewClient:1461553747.503961:1
load:1
Send:1461553747.533862:<0.130.0>:
<stream:stream to="121.43.103.201" xml:lang="*" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client">
Recv:1461553747.790569:<0.130.0>:<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="im.ebnew.com" id="bea48270" xml:lang="*" version="1.0">
Send:1461553751.805212:<0.130.0>:<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" resource="JMeter">ADE0MTIxMTEwMDAwADExMTExMQ==</auth>
Recv:1461553751.833553:<0.130.0>:
<success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">22000496@im.ebnew.com/JMeter</success>
Send:1461553755.847119:<0.130.0>:stopstopstop
Recv:1461553845.885937:<0.130.0>:
<iq type="get" id="71-50" from="im.ebnew.com" to="22000496@im.ebnew.com/JMeter"><ping xmlns="urn:xmpp:ping"/></iq>
EndClient:1461553845.887079:1
load:0**
The content only has the "Send" and "Recv" label,but it doen't contain the  value of the variable loginTag,if i want to verify the variable loginTag's value,i've to send a requeset like this:
`<request subst="true">%%_loginTag%%</request>`
I've tried to find the solution as the manual writed:
"For REALLY verbose logging, recompile tsung with make debug and set loglevel to debug."
but it does not take effect .

**Comment by nniclausse** [comment]
There are two different files: the tsung.dump contains what is sent/received. The example you gave does not correspond to your example xml. 

If i use your example against an echo server, i have this:
Send:1461601031.734556:<0.128.0>:<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" resource="JMeter">ADE0MTIxMTEwMDAwADExMTExMQ==</auth>
Recv:1461601031.734952:<0.128.0>:<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" resource="JMeter">ADE0MTIxMTEwMDAwADExMTExMQ==</auth>


If you recompile tsung with debug, the controller log file will contain many more output (tsung_controller@XXXX), and you will see if your dyn_variable is set or not, for ex. if does not match:

 =INFO REPORT==== 25-Apr-2016::18:17:11 ===
           ts_search:(5:<0.128.0>) Dyn Var (RE): no Match (varname=loginTag),

**Comment by alicehanhy** [comment]
Ok,i've found the verbose loging in the controller log file(tsung_controller@XXXX),thx.
I'm so sorry to that because of the TextEdit tool,the tsung.dump content is incomplete.The complete content is like this:
`Send:1461574571.40885:<0.131.0>:<stream:stream to="121.43.103.201" xml:lang="*" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client">
Recv:1461574571.664767:<0.131.0>:<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="im.ebnew.com" id="93712a9e" xml:lang="*" version="1.0">
Send:1461574575.671508:<0.131.0>:<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" resource="JMeter">ADE0MTIxMTEwMDAwADExMTExMQ==</auth>
Recv:1461574575.688836:<0.131.0>:<success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">22000496@im.ebnew.com/JMeter</success>`
