### ISSUE TITLE
Unable to start HTTP test

### ISSUE THREAD

**Issue by subbu05** [processone/tsung#169]
I have installed latest TSUNG 1.6 on MAC

Test file (XML):

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tsung SYSTEM "/usr/local/Cellar/tsung/1.6.0/share/tsung/tsung-1.0.dtd" []>
<tsung loglevel="debug">

  <clients>
    <client host="localhost" cpu="2" maxusers="1"/>
  </clients>

  <servers>
    <server host="google.com" port="443" type="tcp"/>
  </servers>

  <load>
    <arrivalphase phase="1" duration="1" unit="minute">
      <users arrivalrate="1" unit="second"/>
    </arrivalphase>
  </load>

  <sessions>
    <session name="es_load" weight="1" type="ts_http">
      <request>
      <http url="/"
              method="GET"
               />
      </request>
    </session>
  </sessions>
</tsung>
```

When I run below command I see its throwing errors as mentioned below:
**tsung -f test.xml start **
Starting Tsung
Log directory is: /Users/sumalepa/.tsung/log/20160426-0952
Can't start ! {error,
                  {{badmatch,{error,enoent}},
                   [{ts_controller_sup,start_inets,1,
                        [{file,"src/tsung_controller/ts_controller_sup.erl"},
                         {line,105}]},
                    {ts_controller_sup,init,1,
                        [{file,"src/tsung_controller/ts_controller_sup.erl"},
                         {line,91}]},
                    {supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},
                    {gen_server,init_it,6,
                        [{file,"gen_server.erl"},{line,328}]},
                    {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,240}]}]}}

**Comment by tisba** [comment]
Hey @subbu05! Your configuration got truncated/unreadable. Do you mind edit your issue and add \`\`\` (https://guides.github.com/features/mastering-markdown/#examples) so that the XML gets preserved?

**Comment by subbu05** [comment]
Thanks Sebastin
I updated the issue with proper formatting of XML.

**Comment by bltb** [comment]
@subbu05 , what Erlang/OTP version are you using on your Mac? e.g.

`Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:8] [kernel-poll:true]`

And, could you please attach or gist all the other logs from the log directory?

**Comment by subbu05** [comment]
Erlang version
erl -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V7.3  (abort with ^G)


All the log files created are empty.
cat .tsung/log/20160426-0920/tsung_controller\@macpc.log

**Comment by bltb** [comment]
I reproduced your error. :smile: 

```
rm -rf /tmp/t/share/tsung/templates/style


/tmp/t/bin/tsung -f test.xml start       
Starting Tsung
Log directory is: /home/blt/.tsung/log/20160427-1858
Can't start ! {error,
                  {{badmatch,{error,enoent}},
                   [{ts_controller_sup,start_inets,1,
                        [{file,"src/tsung_controller/ts_controller_sup.erl"},
                         {line,105}]},
                    {ts_controller_sup,init,1,
                        [{file,"src/tsung_controller/ts_controller_sup.erl"},
                         {line,91}]},
                    {supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},
                    {gen_server,init_it,6,
                        [{file,"gen_server.erl"},{line,328}]},
                    {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,240}]}]}} 


```

**Comment by subbu05** [comment]
What is solution/fix for this?

**Comment by nniclausse** [comment]
It seems there are some missing files in your installation.  I tried to run tsung (installed by brew) on a mac, and it works. Can you  print the content of  "find /usr/local/Cellar/tsung/1.6.0" ?

**Comment by subbu05** [comment]
I re-installed tsung and works fine on the mac os.
Thank you all for helping me to get resolved.

**Comment by divfor** [comment]
http://git.net/ml/ubuntu-bugs/2016-10/msg08784.html
it says:
* Running Tsung requires it to find the path 
"../../../../../share/tsung/templates/style" in order to show the web UI
* Tsung binaries are installed to 
/usr/lib/x86_64-linux-gnu/erlang/lib/tsung_controller-1.6.0/ebin
* Share path is at /usr/share/tsung/templates/style/

from Ubuntu 17.04 I made below links to have it works:
ln -s /usr/share /usr/lib/share
ln -s /usr/lib/x86_64-linux-gnu/tsung /usr/lib/tsung

**Comment by hungpt297** [comment]
@divfor, many thanks. It worked.

**Comment by mass10** [comment]
Great! It worked.

```
Linux instance-1 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
```

**Comment by Varanishe** [comment]
Hello? i faced with the same issue on cent os 7, 
 {error,
                  {{badmatch,{error,enoent}},
                   [{ts_controller_sup,start_inets,2,
                        [{file,"src/tsung_controller/ts_controller_sup.erl"},
                         {line,109}]},
                    {ts_controller_sup,init,1,
                        [{file,"src/tsung_controller/ts_controller_sup.erl"},
                         {line,94}]},
                    {supervisor,init,1,[{file,"supervisor.erl"},{line,239}]},
                    {gen_server,init_it,6,
                        [{file,"gen_server.erl"},{line,304}]},
                    {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,239}]}]}}
