### ISSUE TITLE
Access to web GUI from a CLI

### ISSUE THREAD

**Issue by KiarashS** [processone/tsung#181]
Dear,

I have a topology which constructed with Mininet, i use tsung in one of topology nodes, but i can not access to web GUI from localhost.

How i can connect to tsung web GUI from localhost(root namespace) which executed in a CLI (maybe isolated namespace)?

Thanks for tsung tool, and thanks in advance for your help.

**Comment by subbu05** [comment]
http://<Controller-IP>:8091/

Make sure you have access to port 8091.
