### ISSUE TITLE
How to send newline characater in ts_raw

### ISSUE THREAD

**Issue by goofansu** [processone/tsung#188]
```
<request>
          <raw data="hello\n" ack="no_ack" />
</request>
```

'\n' above will be replaced with `\\n`, how to avoid the auto escape?

PS: I'm sending raw tcp packets to test our ELK performance. The logstash's tcp input required newline to split events.

Thanks

**Comment by tisba** [comment]
I believe `&#10;` is used in XML to encode newlines in attributes.

**Comment by goofansu** [comment]
That's it, thanks
