### ISSUE TITLE
Recursive Download Html Page and Its Contents

### ISSUE THREAD

**Issue by KiarashS** [processone/tsung#192]
Dear,

I want to recursively download total html file and it's js files, css files, fonts and images, How i can do this work?
Currently when tsung send request to a html page, just download that html page and doesn't download  js files, css files, fonts and images and etc which included in that html page!

Thanks

**Comment by vguardiola** [comment]
For this job the best way is use wget, for exemple:

wget -r -np -k http://www.yourdomain.com/

**Comment by KiarashS** [comment]
@vguardiola No, I want use Recursive Download **In** tsung.

How i can Recursive Download Html Page and Its Contents **Inside** tsung.

**Comment by vguardiola** [comment]
I don't know, today is my first day using tsung, sorry

**Comment by nniclausse** [comment]
Tsung is not really designed to parse the HTML (having hundreds of simultaneous processes parsing html on a single machine would be very slow) . You should use the tsung recorder once to record a session , customize it if needed, and then use tsung to replay the session.

If you really need this, you can use a dynamic variable and the xpath parser:
http://tsung.erlang-projects.org/user_manual/conf-advanced-features.html#xpath

e.g., to get all `<link href="xxxx">`

    <request>
      <dyn_variable name='urls' xpath='//link/@href'/>
      <http url='/index.html' method='GET'></http>
    </request>

    <foreach name="url" in="urls" >
        <request subst="true">
          <http url='%%_url%%'  method='GET'></http>
        </request>
    </foreach>
