### ISSUE TITLE
change_type dynamic substitution

### ISSUE THREAD

**Issue by zanni** [processone/tsung#196]
I need to open a web socket connection using host/port information retrieved in a previously done HTTP request and set as dyn_variable.
I would like to use substitution pattern (%%_myVar%%) in <change_type> host/port attributes like:
```xml
   <change_type new_type="ts_websocket" server_type="tcp" host="%%_myServer%%" port="%%_myPort%%"  store="true" restore="true" bidi="true"/>
```
But using this notation triggers the following error:
```
Config Error, aborting ! {fatal,{{error,{validity_constraint_Name_Token,37}},
                                 {file,"tsung_benchmark.xml"},
                                 {line,53},
                                 {col,69}}}
```
Substitution patterns are not explicitly used in change_type documentation/exemples so I wondering if it's even possible but this merge (https://github.com/processone/tsung/pull/12/commits/1c6fdbb2591f2a18e2ad5fe6934b1b7767e5d422) make me think it was.

**Comment by nniclausse** [comment]
You are right, it's a regression. fixed in e9b3ce2b396a7ea2fe6816a40b235b7b9e4c0e2a
thanks for reporting the bug.
