### ISSUE TITLE
Mix test envoirments (http, XMPP)

### ISSUE THREAD

**Issue by vguardiola** [processone/tsung#197]
Hi, I need to do a previous call to a Http endpoint and read some data before do a login in a XMPP server, and use this data for the login, is it possible?

**Comment by nniclausse** [comment]
Yes, use a dynamic_variable and change_type, see: http://tsung.erlang-projects.org/user_manual/conf-sessions.html#mixing-session-type

**Comment by vguardiola** [comment]
I searched and search in the docs but I didn't see it, I need to clean my goggles.

Thanks

**Comment by tisba** [comment]
@vguardiola Where did you start looking? Would be great, if you could suggest a improve to the docs…

**Comment by vguardiola** [comment]
The problem was that I stop to read on Jabber section. I think that the trasnversal information about session may be on the top of the page.
