### ISSUE TITLE
Questions about testing mqtt

### ISSUE THREAD

**Issue by LichFaker** [processone/tsung#199]
1. Is tsung1.6.0 support mqtt3.1.1?

2. I have no idea about how to test mqtt for user and password,where can I found an example?

**Comment by nniclausse** [comment]
Hi
1/ i'm not familiar with the new features of MQTT  3.1.1, so i don't know. Did you test it ?
2/ Indeed, the documentation fails to mention the  **username** and **password** attributes of the _connect_ request. fixed !

**Comment by LichFaker** [comment]
@nniclausse It's not support mqtt3.1.1
