### ISSUE TITLE
Tsung: Single chat - Both online and offline users not working

### ISSUE THREAD

**Issue by svenkey** [processone/tsung#200]
Hi All,
I am new to tsung tool to test xmpp protocol.

When i am doing single chat with online destination alone it is working fine that is single chat conversation going good. But, when i tried with both online and offline destination such time both online and offline are not working fine. I am getting error as error_no_offline. When i checked the database, message not delivered for online users also.

Please review and assist on this issues to resolve it.

Please find the script file and statistics report for your reference.

Regards,

Venkey
[Tsung - Stats Report 120916.pdf](https://github.com/processone/tsung/files/466621/Tsung.-.Stats.Report.120916.pdf)

[Single chat offline issue.txt](https://github.com/processone/tsung/files/466659/Single.chat.offline.issue.txt)

**Comment by nniclausse** [comment]
you have configured only 2 xmpp users (userid_max), and starts 5 sessions, so as soon as the first two sessions are started (and presence is sent), no offline users will be left. userid_max should be > to the number of started sessions in order to have some offline users available.

**Comment by svenkey** [comment]
Hi Nicolas,

Thanks to reply. I will check it and will do necessary action.

Regards,
-- 
Venkatesh S


This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please delete it right away or
notify the sender.

**Comment by svenkey** [comment]
Hi Nicolas,

As per your advise, we changed in script and executed the test for the project. Now, we are getting expecting out put without any error.

Thanks for your assistance.

Regards,
Venkey.
