### ISSUE TITLE
Timeout won't apply unless something happen to socket

### ISSUE THREAD

**Issue by reith** [processone/tsung#204]
I had an issue with timeout being not applied which is discussed in [this thread](http://lists.process-one.net/pipermail/tsung-users/2016-September/003533.html).  My case is a DNS stress loader [hosted here](https://github.com/reith/tsung_dns).

The problem is ts_client checks timeout always after `handle_data_msg` that I think (by [this line](https://github.com/processone/tsung/blob/master/src/tsung/ts_client.erl#L241) but not sure about [this](https://github.com/processone/tsung/blob/master/src/tsung/ts_client.erl#L212)) would happen just when some message got from socket.  This may never happen for a UDP socket.

I think there should be a timer in ts_client itself to send timeout message after `idle_timeout` or `global_ack_timeout`.

**Comment by nniclausse** [comment]
you are right, now the idle_timeout  timer is triggered after a message is sent;  thanks
