### ISSUE TITLE
How to pass dynamic variable from one session to another

### ISSUE THREAD

**Issue by subbu05** [processone/tsung#215]
We have scenario when response of 1st request in session to be used in 2nd request in another session. Reason for having two separate sessions is we have different certificates for each request.

**Comment by bltb** [comment]
Maybe this question would be better directed to the mailing list with some details?

https://lists.process-one.net/mailman/listinfo/tsung-users

**Comment by bltb** [comment]
Maybe this question would be better directed to the mailing list with some details?

https://lists.process-one.net/mailman/listinfo/tsung-users
