### ISSUE TITLE
Does tsung support TLS/SSL load testing for MQTT?

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [processone/tsung#221]
Tsung has a support for TLS/SSL for MQTT?

**Comment by nniclausse** [comment]
yes, use the 'ssl type in server, e.g.'    <server host="my-mqttt-server-hostname" port="8883" type="ssl" />

**Comment by SkyZySR** [comment]
I got error with ssl_not_started. 

ts_client:(6:<0.12892.0>) (Re)connect from 0.0.0.0:0 to example.com:5533, Error: ssl_not_started
