### ISSUE TITLE
stop entire test execution in do=

### ISSUE THREAD

**Issue by dechaoz05** [processone/tsung#225]
requesting a feature to stop test execution (not just session). something like:
`<match do="abort_test" when="nomatch">200 OK</match>`

**Comment by tisba** [comment]
I'd like to second that.

I think it would even be nice to have a `<abort />` element, so that you can abort not only in conjunction with a single test, but also use conditionals (`<if>`) and other logic.

**Comment by tisba** [comment]
Is there currently a way to abort the current user/session as well, @nniclausse?

**Comment by nniclausse** [comment]
you can abort a session on a <match do='abort' ...>

**Comment by tisba** [comment]
But match only works in context of a request. I cannot abort the session based on <if> e.g.

**Comment by tisba** [comment]
damn, I totally overlooked this change! Thanks! ❤️
