### ISSUE TITLE
I have a lot of error_unknown 

### ISSUE THREAD

**Issue by DavidCarro** [processone/tsung#230]
I do a simulation and I have a lot of error_unknown. I don´t understand why. 
I put my .xml file and the erroros graph. Can anybody help me? Thanks

![eror_samplexml](https://cloud.githubusercontent.com/assets/26599513/24198418/27b29d76-0f06-11e7-82c0-e82c689a0a5f.png)

![unknown_errors](https://cloud.githubusercontent.com/assets/26599513/24198306/a05de3c6-0f05-11e7-9bd3-08d470c75845.png)

**Comment by nniclausse** [comment]
You will have more details in the log files; it can happen if your tsung clients are overloaded

**Comment by tisba** [comment]
IIRC there were some fixes causing `error_unknown` to be reported, instead of a more useful error.

@DavidCarro are you still running into these issues? What version of Tsung are you using? And as @nniclausse pointed out, do you have some info on the tsung client resource/CPU utilisation?

**Comment by tisba** [comment]
Without more information, like Tsung & Erlang version, logs, Tsung config XMLs it is next to impossible to help.

As already mentioned, current develop contains a few fixes around `error_unknown` which might already help.

@DavidCarro please feel free to comment here again if you can provide more information or if your problem persists. Thanks you!
