### ISSUE TITLE
Web dashboard reports/graph section blank

### ISSUE THREAD

**Issue by ashleyconnor** [processone/tsung#252]
Summary:

Installed tsung via homebrew. Ran `tsung -f tsung.xml -k start` - which is correctly load testing my application (logs stream), I then visit web dashboard on `localhost:8091` and click `Graphs/Reports`.

Expected to see: reports. Result. Screenshot below.

<img width="1436" alt="screen shot 2017-08-12 at 13 26 46" src="https://user-images.githubusercontent.com/458214/29242839-02ca1652-7f62-11e7-8e41-6ad82ec97020.png">

tsung version: `1.6`

### tsung.xml
```
<?xml version="1.0"?>
<!DOCTYPE tsung SYSTEM "/usr/local/Cellar/tsung/1.6.0/share/tsung/tsung-1.0.dtd">
<tsung loglevel="warning">

  <clients>
    <client host="localhost" cpu="1" use_controller_vm="true" maxusers="10000"/>
  </clients>

  <servers>
    <server host="localhost" port="7312" type="tcp"/>
  </servers>

  <load>
    <arrivalphase phase="1" duration="100" unit="second">
      <users maxnumber="1500" arrivalrate="200" unit="second"/>
    </arrivalphase>
  </load>

  <options>
    <option name="ports_range" min="1025" max="65535"/>
  </options>

  <sessions>
    <session name="es_load" weight="1" type="ts_http">
      <request>
      <http url="/v1/index"
        method="GET" />
      </request>
    </session>
  </sessions>
</tsung>
```

OS: `OSX 10.12.6`
ErlangVM: `Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]`

[http://www.thegreatcodeadventure.com/load-testing-rails-5-action-cable-with-tsung/](http://www.thegreatcodeadventure.com/load-testing-rails-5-action-cable-with-tsung/)

**Comment by ashleyconnor** [comment]
Typical of me. Figured it out 5 mins later.

I was expecting to see the error mentioned in the blog post:

```
Can't locate Template.pm in @INC (you may need to install the Template module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/lib/tsung/bin/tsung_stats.pl line 570.  
```

I didn't see it from running the server but I did see it when I `cd` into the output directory and ran `/usr/local/lib/tsung/bin/tsung_stats.pl`. Followed the blog poster's instructions.

`sudo cpan Template` - Got errors when trying to install the C extension (it will prompt you) so opted for Perl instead, which worked.

Re-running the web dashboard after all this produces the graphs and reports.

**Comment by iamMrGaurav** [comment]
Why this are not being shown ?
<img width="1440" alt="Screenshot 2024-03-21 at 2 15 16 PM" src="https://github.com/processone/tsung/assets/64460040/d51e4ccc-3512-416a-9b27-567705ba22bf">
<img width="1440" alt="Screenshot 2024-03-21 at 2 15 23 PM" src="https://github.com/processone/tsung/assets/64460040/207de7ed-ec1d-4772-8371-f505c4539978">

**Comment by lewisHeath** [comment]
Hey did you ever solve this? same issue here
