### ISSUE TITLE
List of all system dynamic variables

### ISSUE THREAD

**Issue by woj-tek** [processone/tsung#254]
Is there a list of all system, dynamic variables? I would like to get username/password of current user but I don't even know where to start the search and documentation doesn't seem to have this information.

**Comment by tisba** [comment]
What do you mean with "username/password"? Don't you have to provide that in order to test your system/API? (btw, which protocol are you testing?)

**Comment by woj-tek** [comment]
I was testing XMPP. And I've managed to get the information I needed from `Pid`:
```
                <setdynvars sourcetype="eval" code='fun({Pid,DynVars}) ->
                        Username = element(5,Pid),
                        …
                </setdynvars>
```

**Comment by tisba** [comment]
Cool!

Actually the tuple you are using is `{Session,Dynvars}` (not `{Pid,Dynvars}`). I think it was the process pid a couple of tsung versions back.

**Comment by woj-tek** [comment]
I was a while back and I was very-very-very not familiar with Erlang so it was a bit of hammering out but it worked ;)

**Comment by tisba** [comment]
I'm closing this for now. If you have another question, feel free to comment, @woj-tek!
