### ISSUE TITLE
Tsung sometimes replaces first host character with "-"

### ISSUE THREAD

**Issue by manukoshe** [processone/tsung#257]
I am having this strange issue after successfully using tsung for many times. Sometimes in requests I see that instead of "hostname.something.com" tsung is actually generating requests to  "-ostname.something.com". 

Did anyone have this issue?

**Comment by tisba** [comment]
Are you using the proxy recorder? I think this is used an indication if the request was made via HTTPs.

**Comment by manukoshe** [comment]
Solved this. Such problem arises when in variables .csv file there is empty line.  Accidentally put a new line at the end of file and it took a while to figure out what's wrong...
