### ISSUE TITLE
MQTT over Websockets

### ISSUE THREAD

**Issue by Cameron-Rowshanbin-ConnectedLab** [processone/tsung#259]
I'm looking to use tsung to test our mqtt server. Clients connect to the server over websockets and I'm looking for a way to simulate that with tsung. From what I can see in the documentation, we specify the protocol in the <session type=...> tag, where type can be either 'ts_websocket' or 'ts_mqtt'.

Is there any support for mqtt over websockets?

**Comment by nniclausse** [comment]
You can try to use a <server> with type="websocket" (instead of tcp) and ts_mqtt.

**Comment by tisba** [comment]
@nniclausse are you sure this works as expected? I'm not entirely sure, but I always assumed that the mqtt protocol changes slightly, when transported over websockets.

**Comment by tisba** [comment]
Did this solve your problem, @Cameron-Rowshanbin-ConnectedLab?

**Comment by tisba** [comment]
I cannot confirm this issue. I've tested MQTT over WebSocket using tsung 1.7.0 and talking to `test.mosquitto.org` which appears to work just fine.

@Cameron-Rowshanbin-ConnectedLab: If the problem still persists, please feel free to open a new issue or reply here with more details on your issue (Tsung & Erlang version, Tsung XML configuration, error logs, …).
