### ISSUE TITLE
"Direct IP" option forces traffic for tsung_controller.

### ISSUE THREAD

**Issue by loguntsov** [processone/tsung#267]
There is description of Direct IP feature:
http://tsung.erlang-projects.org/user_manual/conf-client-server.html#direct-ip

I have benchmark system based on tsung 1.6.0. I tried update it to 1.7.0 and met problem.

So when i posted option: -I IP_of_tsung_controller.
I see all traffic load on this controller machine. WTF?

When i posted -I IP_of_server_for_load_test i gets this in logs of report:
=ERROR REPORT==== 14-Nov-2017::15:43:12 ===
** Generic server ts_config_server terminating
** Last message in was {'$gen_cast',{newbeams,['47.100.13.194']}}
** When Server state == {state,
                         {config,undefined,680,6,none,text,undefined,
                          [{client,"47.100.13.194",1.0,60000,[],undefined}],
                          [{server,"172.19.214.12",5222,ts_tcp,1}],
                          undefined,[],
                          [{arrivalphase,1,680000,undefined,0.1,110000,0,[],
                            false,1}],
                          undefined,false,[],[],ts_jabber_oncam,
                          [{session,1,100,ts_jabber_oncam,"socket",true,
                            false,10000,
                            {proto_opts,negotiate,negotiate,"/http-bind/",
                             false,false,false,"/chat","binary",[],10,3,
                             600000,infinity,infinity,32768,32768,32768,32768,
                             [],true,true},
                            undefined,22,undefined,undefined,undefined,
                            undefined,undefined}],
                          [],61472,false,1,22,22,
                          [{userlist,
                            "/root/ejabberd/script-test/tsung-test/tsung_logins_per_sec/data/users_u110000_r500.csv"}],
                          0,10000,
                          {proto_opts,negotiate,negotiate,"/http-bind/",
                           false,false,false,"/chat","binary",[],10,3,600000,
                           infinity,infinity,32768,32768,32768,32768,[],true,
                           true},
                          now,none,110000,[],undefined,"d",false,1,undefined,
                          20,[]},
                         "/root/ejabberd/script-test/tsung-test/tsung_logins_per_sec/report/test_u110000_r500/20171114-1542",
                         0,0,[],undefined,1,undefined,'172.19.214.12',0,0,
                         undefined,1.0}
** Reason for termination ==
** {{slave_failure,timeout},

So i don't understand real behavior for this option.
Could you explain me this with some examples ?

Thanks.

**Comment by loguntsov** [comment]
How i can test cluster of server with this option ?

**Comment by loguntsov** [comment]
So as i understood. tsung -I <IP> will generate traffic for same server as tsung_controller and will ignore section <servers> in config. Am i right?
How i can use section <servers> with IP of clients (without names of nodes) ?

**Comment by nniclausse** [comment]
-I option should be used if you don't want to use hostnames and domain names for the erlang distributed settings. If your controller IP (as set in -I <IP>) is not used in the <client> section, it should not send traffic to the servers . Can you show your <client> config ?

**Comment by loguntsov** [comment]
Hi. Thanks for your answer.
I have my own worker which based on old wersion of ts_jabber.erl. So i just updated from new sources of ts_jabber.erl. it work fine right now.
You can close this ticket.
Thank you one more time
