### ISSUE TITLE
how to monitor the server?

### ISSUE THREAD

**Issue by BrentHuang** [processone/tsung#269]
I run tsung on client, and test the server. How to monitor the server? Can tsung do the server monitoring?

**Comment by MrAta** [comment]
If you mean monitoring the statistics in real-time, just run tsung with -k flag and open the http://node-ip:8091/ in a browser.

**Comment by tisba** [comment]
My guess would be, that you are interested in https://tsung.readthedocs.io/en/latest/conf-monitoring.html, right @BrentHuang?

**Comment by tisba** [comment]
@BrentHuang If you have more questions or still problem with this, please comment/re-open!

**Comment by arjunmayilvaganan** [comment]
@tisba I want to monitor the server metrics.
This <https://tsung.readthedocs.io/en/latest/conf-monitoring.html> certainly seems useful.
Now, I'm able to `ssh user@remote_ip` successfully from client to server.

```
  <monitoring>
   <monitor host="remote_ip_address" type="erlang"></monitor>
  <monitoring>
```
Should I also specify username?
Anything else I'm missing?

I'm getting `ssh: connect to host 13 port 22: Invalid argument` error.
Kindly help.

**Comment by mrbartchris** [comment]
HI all, is it possible to monitor a local server? I have an Erlang server which I am hosting locally and want to monitor its performance (CPU usage, memory usage, etc.). How can this (if possible) be done?

**Comment by tisba** [comment]
@arjunmayilvaganan When you generate the reports, there should be sections with graphing the monitoring data as well.

@mrbartchris Can you please elaborate? https://tsung.readthedocs.io/en/latest/conf-monitoring.html describes all available monitoring options during a tsung run.

**Comment by mrbartchris** [comment]
@tisba so I have an Erlang server which I am hosting locally and want to monitor its performance, i.e. get information about from the OS using the PID of that server. In JMeter, I did this by specifying the PID of which process I want to be monitored. Is this possible to do using Tsung? If so, how can it be done? Thanks in advance.

**Comment by tisba** [comment]
AFAIK you can only monitor the entire host, not specific processes. The goal of tsungs monitoring is not to provide a comprehensive performance monitoring solution.

If you are interested in more specific monitoring, you should probably take a look into a dedicated tool, especially if you are interested in application performance monitoring.

**Comment by mrbartchris** [comment]
@tisba Do you have any recommendations for this type of performance monitoring?

**Comment by tisba** [comment]
No, not really. But there are as many solutions out there as there are special use cases…
