### ISSUE TITLE
Why Tsung showing Host Machine's CPU and Memory Usage?

### ISSUE THREAD

**Issue by rajuniit** [processone/tsung#280]
Hi
I added a monitoring section to get usage of remote server's cpu and memory. But it is always showing host machine's cpu and memory usage.

Is there anything I need to do for it?

For xml file config

<clients>
        <client host="localhost" use_controller_vm="true" maxusers="500"/>
    </clients>

    <servers>
        <server host="appserver" port="8080" type="tcp"/>
    </servers>

    <monitoring>
        <monitor host="appserver" type="erlang"></monitor>
    </monitoring>

**Comment by tisba** [comment]
Hey @rajuniit. Are you only seeing the host/controller? Or also the target you want to monitor?

**Comment by rajuniit** [comment]
@tisba thanks for your comment. Actually my problem has been resolved. It is now showing target machine's cpu and memory usage using munin. 

But I have one more question, Can I exclude the host machine's cpu/memory usage from the report. Because It makes some confusion to me.

**Comment by tisba** [comment]
I personally think it's very good that the host/controller is included as well. I've seen it many times that monitoring of the load generator setup itself was forgotten or neglected and the test results were heavily screwed by this fact.

So my strong advice is to always monitor all components involved when testing.
