### ISSUE TITLE
can I specify the server process's CPU and memory usage to be monitored rather then the server's whole CPU and memory usage?

### ISSUE THREAD

**Issue by hui6075** [processone/tsung#283]
And is there any way to gather the statistic about mqtt broker forwarding latency? Thank you!

**Comment by tisba** [comment]
AFAIK there is no way to do that. The monitoring aims at looking at the entire system.

For the question regarding MQTT, I don't know :)

**Comment by hui6075** [comment]
@tisba thanks, I would like to give a such enhancement about tsung;)
