### ISSUE TITLE
how to set clientID in mqtt connect？

### ISSUE THREAD

**Issue by DanmyWei** [processone/tsung#293]
does mqtt plugin support to set option with given clientid for each connection and how?  thanks for your reply

**Comment by sesposito** [comment]
I'm trying to create some tests for MQTT where I need to use a custom clientId and I noticed that it is not accepted as an argument in connect.

**Comment by tisba** [comment]
@DanmyWei, @sesposito does https://github.com/processone/tsung/pull/303 fix your issue?
