### ISSUE TITLE
Apache Log Replay with log2tsung.pl

### ISSUE THREAD

**Issue by nikhilshah28** [processone/tsung#306]
I am getting into utilizing Tsung for a client and was hoping that Tsung had a tool such as apache log sampler, which allows you to feed in apache access logs and replay them using Tsung. I haven't come across anything and was hoping you can provide me with some insight,

**Comment by tisba** [comment]
I never tried it, but there is [log2tsung.pl](https://github.com/processone/tsung/blob/develop/src/log2tsung.pl.in) included in tsung. You could give this a try if your log format matches.

**Comment by nikhilshah28** [comment]
I was able to get this working. Initially, I tried to download the log2tsung.pl from this github repo onto the server directly, but ran into some PERL error messages :
```Global symbol "@prefix" requires explicit package name (did you forget to declare "my @prefix"?) at log2tsung.pl line 46.
Global symbol "@datadir" requires explicit package name (did you forget to declare "my @datadir"?) at log2tsung.pl line 47.
Global symbol "@DTD" requires explicit package name (did you forget to declare "my @DTD"?) at log2tsung.pl line 47.```

I then realized that I in fact did compile Tsung from source rather than installing from repos, so was able to find the log2tsung.pl script in the /home/ubuntu/.tsung/src/ directory and attempted to run it from there, which did NOT throw any errors when running `perl log2tsung.pl --help`. 

I copied over an apache log file, and ran `perl log2tsung apache.log` and it actually outputs an XML format of the tsung config file (you can pass in options, I chose not to as I was just testing)

**Comment by tisba** [comment]
Thank you for sharing! Also glad you've found a solution to your problem :)
