### ISSUE TITLE
Cannot run Tsung on Alpine Docker Image

### ISSUE THREAD

**Issue by freitzzz** [processone/tsung#335]
Hello everyone.

I'm creating a dockerfile to optimize the run of a stress test to an API with the power of Tsung.

Yet, as I start Tsung in an Alpine Docker image the following error occurs:

`` {"init terminating in do_boot",{{app_start_failed,asn1,{"no such file or directory","asn1.app"}},[{ts_utils,start_ok,3,[{file,"src/tsung/ts_utils.erl"},{line,1007}]},{ts_utils,start_ok,3,[{file,"src/tsung/ts_utils.erl"},{line,1004}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{app_start_failed,asn1,{no such file or directory,asn1.app}},[{ts_utils,start_ok,3,[{_},{_}]},{ts_utils,start_ok,3,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}) ``

This is my dockerfile so far:

` FROM alpine:latest

COPY ./myc_api_stress.xml /tsung/stress_files/myc_api_stress.xml

RUN echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories &&\
    apk add --no-cache tsung@testing
EXPOSE 8091

ENTRYPOINT ["tsung"]`

I assume the problem is with Alpine Erlang dependencies, since I can run Tsung with the same XML file on my laptop running Lubuntu 18.04

Sorry for my newbish with Docker

**Comment by freitzzz** [comment]
Was missing some dependencies during install, closing issue

**Comment by tarrenj** [comment]
What dependencies did you have to add?

**Comment by tisba** [comment]
I'm using the following `Dockerfile` for various tests. I'm also thinking about adding this in a re-worked form to the repository as this might be useful for others as well.

```
FROM erlang:20.3

RUN apt-get update && \
  apt-get install -y python python-dev perl libtemplate-perl gnuplot git \
  && wget https://bootstrap.pypa.io/get-pip.py \
  && python get-pip.py \
  && pip install matplotlib

RUN useradd --shell /bin/bash --home-dir /tsung --create-home tsung

COPY --chown=tsung tsung /tsung/src

RUN cd /tsung/src \
  && ./configure --prefix="/tsung/install" \
  && make debug \
  && make install

USER tsung
EXPOSE 8091

ENTRYPOINT ["/tsung/install/bin/tsung"]
```

**Comment by theAkito** [comment]
@freitzzz

Could you please share, what dependencies were missing?

**Comment by joaomagfreitas** [comment]
Hey @theAkito, I’ve long moved from the project I was using Tsung and don’t know what was missing. Sorry for not posting the solution right ahead
