### ISSUE TITLE
I need to understand "Counter Statics" in the report

### ISSUE THREAD

**Issue by MohamadSyafiq94** [processone/tsung#337]
I need to understand "Counter Statics" in the report, and I am interested in knowing 
1. Total concurrent Users
2. Total requests made
3. Total successful and total failed complete.
4. Can anyone explain mean : connected, finish_users_count, users, and users_count
![kk](https://user-images.githubusercontent.com/26862949/48530934-1737a180-e8d5-11e8-9cf7-2bbf224e2db1.jpg)

Thanks

**Comment by tisba** [comment]
This is a bit out of context, but `connected` and `users` refer to counters for a "snapshot" which tsung makes every 10sec. `{finished_users,users}_count` refer to the launched users who have finished their session and the number of launched users.

I hope that helps. Feel free to comment again, if you have another question.
