### ISSUE TITLE
What means error_connect_timeout and how can I log requests with this error?

### ISSUE THREAD

**Issue by juaninf** [processone/tsung#338]
Dear members,

In my tsung.log, I would like to know what means "error_connect_timeout", I think that this error happens when after n unsuccessful connection attempts. That is true?. Other question, Which files I need to modify in order to log the requests with "error_connect_timeout".

Thanks by your attention

**Comment by tisba** [comment]
Hey @juaninf!

So yes, `error_connect_timeout` means that there was an issue connecting to the host. No request has been made yet. You should be able to see more, if you increase the log level to `<tsung loglevel="debug">`. IMO at least the target (host + port) should be logged.

**Comment by tisba** [comment]
I'll close this issue now. Feel free to comment again, if this did not help you to solve your problem.
