### ISSUE TITLE
Generate HTTP Requests without waiting for response

### ISSUE THREAD

**Issue by deanstef** [processone/tsung#356]
I have a tsung script that run K clients which remains active for the entire load duration. Each client run a session with infinite loop to execute request at an approximate rate of 1req/s: `for {request; think=1} `. 

From a preliminary analysis it looks to me that each client waits for responses before running the new request. Hence, if the server response is delayed for any reason, some requests are skipped making impossible to generate a constant rate.

Is this true? If yes, is there any option for clients to execute requests without waiting for responses?

**Comment by deanstef** [comment]
Solved using raw data with `no_ack` instead of HTTP request. I close the issue.

**Comment by hippo-dalaoshe** [comment]
http cannot set ack="no_ack" how to make it？？

**Comment by deanstef** [comment]
Use raw request with no_ack. It will accept any TCP/UDP connection. http://tsung.erlang-projects.org/user_manual/conf-sessions.html#raw

**Comment by hippo-dalaoshe** [comment]
I should  use the raw request to package https meta data? it seems a little troublesome..  can you give me an example ?
