### ISSUE TITLE
Tsung Report is not clear

### ISSUE THREAD

**Issue by sujankumar4593** [processone/tsung#369]
I have performed load test for 1 Lakh concurrent users in Tsung tool. I have generated the html report and viewed the report.

But the values generated for ***tr_authenticate***, ***tr_Chat*** and ***tr_close*** under "**Transaction Statistics**" are not clear. Mean value for 'tr_authenticate' is showing as '**8mn 59sec**' but it will not take that much long time. For tr_Chat & tr_close transactions also Mean value is high.

Below I have mentioned the load progression for reference,

```
<load>
  <arrivalphase phase="1" duration="60" unit="minute">
    <users maxnumber="100000" arrivalrate="100" unit="second"/>
  </arrivalphase>
</load>
```

Please look into the attached screenshot of the 'Transaction Statistics' and explain me *how the values are generated* for those transactions in the report.

Note: I have attached 'tsung-report.png' file here for the reference.
![tsung-report](https://user-images.githubusercontent.com/8556194/72207122-97e33500-34bb-11ea-98d4-a3d8d5f62db6.png)

**Comment by mremond** [comment]
Well it depends on the scenario and the behaviour of the test. If there is some failures or if scenario goes into dead end, it can mess the result.
